package worktree

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/edwardmontoya/circle/internal/compose"
)

// OverrideFile is what Circle writes into the worktree.
//
// Compose merges docker-compose.override.yml automatically, so the user's own
// compose file is never edited. That matters: bb-control publishes "8000:8000"
// as a literal, which no .env variable can override — the override file is the
// only mechanism that remaps a hard-coded port without rewriting the source.
const OverrideFile = "docker-compose.override.yml"

// MapFile records what was allocated, for the session and for `circle run`.
const MapFile = "compose.map.toml"

// Plan is what provisioning will do, before it does it.
type Plan struct {
	Item     string
	Project  string
	Worktree string
	Compose  string
	Ports    []Remap
	// Skipped holds port entries that could not be parsed. They are surfaced
	// loudly: a stack reported as isolated while one port still collides is
	// worse than an honest refusal.
	Skipped map[string][]string
}

// Remap is one host port moved out of the way.
type Remap struct {
	Service   string
	Container int
	From      int
	To        int
	Bind      string
}

func key(p compose.Port) string { return fmt.Sprintf("%s:%d", p.Service, p.Container) }

// BuildPlan works out the remapping without touching the disk.
func BuildPlan(worktreeDir, composePath, item string, lo, hi int) (Plan, error) {
	cf, err := compose.Parse(composePath)
	if err != nil {
		return Plan{}, fmt.Errorf("parsing %s: %w", composePath, err)
	}
	published := cf.PublishedPorts()

	plan := Plan{
		Item:     item,
		Project:  ProjectName(item),
		Worktree: worktreeDir,
		Compose:  composePath,
		Skipped:  cf.Unparseable(),
	}
	if len(published) == 0 {
		return plan, nil
	}

	keys := make([]string, 0, len(published))
	for _, p := range published {
		keys = append(keys, key(p))
	}
	lease, err := Allocate(worktreeDir, item, plan.Project, worktreeDir, keys, lo, hi)
	if err != nil {
		return plan, err
	}
	for _, p := range published {
		to, ok := lease.Ports[key(p)]
		if !ok {
			continue
		}
		plan.Ports = append(plan.Ports, Remap{
			Service: p.Service, Container: p.Container, From: p.Host, To: to, Bind: p.Bind,
		})
	}
	sort.Slice(plan.Ports, func(i, j int) bool { return plan.Ports[i].To < plan.Ports[j].To })
	return plan, nil
}

// ProjectName namespaces networks, volumes and container names.
//
// Compose derives all three from the project name, so setting it is what makes
// two stacks of the same repo genuinely independent rather than merely
// differently-ported.
func ProjectName(item string) string {
	safe := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			return r
		case r >= 'A' && r <= 'Z':
			return r + 32
		default:
			return '-'
		}
	}, item)
	return "circle-" + strings.Trim(safe, "-")
}

// Apply writes the override, the env file and the map.
func Apply(p Plan) error {
	if err := os.WriteFile(filepath.Join(p.Worktree, OverrideFile),
		[]byte(RenderOverride(p)), 0o644); err != nil {
		return err
	}
	// COMPOSE_PROJECT_NAME in .env is read by compose automatically, so every
	// `docker compose` invocation in this worktree is namespaced without the
	// caller having to remember a flag.
	env := filepath.Join(p.Worktree, ".env")
	if err := upsertEnv(env, "COMPOSE_PROJECT_NAME", p.Project); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(p.Worktree, ".circle", MapFile),
		[]byte(RenderMap(p)), 0o644)
}

// RenderOverride emits the compose override.
func RenderOverride(p Plan) string {
	var b strings.Builder
	b.WriteString("# Generated by circle. Do not edit; regenerated on provision.\n")
	b.WriteString("#\n")
	b.WriteString("# Compose merges this over your docker-compose.yml automatically, so the\n")
	b.WriteString("# source file is never modified. Host ports are moved into the range the\n")
	b.WriteString("# execution contract reserves, which is what lets several worktrees of this\n")
	b.WriteString("# repository run at once.\n")
	b.WriteString("#\n")
	b.WriteString("# `!override` is load-bearing. Compose's default merge strategy for a\n")
	b.WriteString("# sequence is to APPEND, so without it the original host port stays\n")
	b.WriteString("# published alongside the new one and two worktrees still collide — a\n")
	b.WriteString("# stack that reads as isolated and is not. Requires Compose v2.24+.\n")
	if len(p.Ports) == 0 {
		b.WriteString("#\n# Nothing to remap: this compose file publishes no host ports.\n")
		b.WriteString("services: {}\n")
		return b.String()
	}
	b.WriteString("\nservices:\n")

	byService := map[string][]Remap{}
	var names []string
	for _, r := range p.Ports {
		if _, seen := byService[r.Service]; !seen {
			names = append(names, r.Service)
		}
		byService[r.Service] = append(byService[r.Service], r)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "  %s:\n    ports: !override\n", name)
		for _, r := range byService[name] {
			if r.Bind != "" {
				fmt.Fprintf(&b, "      - \"%s:%d:%d\"   # was %d\n", r.Bind, r.To, r.Container, r.From)
			} else {
				fmt.Fprintf(&b, "      - \"%d:%d\"   # was %d\n", r.To, r.Container, r.From)
			}
		}
	}
	return b.String()
}

// RenderMap records the live mapping so workspace.md and `circle run` can quote
// real ports rather than the ones the source file claims.
func RenderMap(p Plan) string {
	var b strings.Builder
	b.WriteString("# Generated by circle. The live port map for this worktree.\n\n")
	fmt.Fprintf(&b, "item     = %q\nproject  = %q\nworktree = %q\n\n", p.Item, p.Project, p.Worktree)
	for _, r := range p.Ports {
		fmt.Fprintf(&b, "[[port]]\nservice   = %q\ncontainer = %d\nhost      = %d\nwas       = %d\n\n",
			r.Service, r.Container, r.To, r.From)
	}
	for svc, entries := range p.Skipped {
		for _, e := range entries {
			fmt.Fprintf(&b, "[[skipped]]\nservice = %q\nentry   = %q\n\n", svc, e)
		}
	}
	return b.String()
}

// upsertEnv sets one key in a .env file, preserving everything else.
//
// The worktree may already have a .env carried in by .worktreeinclude, and
// clobbering it would take the developer's own configuration with it.
func upsertEnv(path, k, v string) error {
	line := k + "=" + v
	b, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return os.WriteFile(path, []byte(line+"\n"), 0o644)
	}
	lines := strings.Split(strings.TrimRight(string(b), "\n"), "\n")
	found := false
	for i, l := range lines {
		if strings.HasPrefix(strings.TrimSpace(l), k+"=") {
			lines[i] = line
			found = true
			break
		}
	}
	if !found {
		lines = append(lines, line)
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o644)
}

// Down brings a provisioned stack down, volumes included.
//
// Volumes are namespaced by project name, so `-v` removes only this worktree's
// data. Leaving them behind is what produces the orphan volumes the PRD's Phase
// 3 exit criterion forbids.
func Down(worktreeDir, project, composePath string) error {
	cmd := exec.Command("docker", "compose", "-p", project, "-f", composePath, "down", "-v")
	cmd.Dir = worktreeDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("docker compose down: %s", strings.TrimSpace(string(out)))
	}
	return nil
}
