package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/edwardmontoya/circle/internal/brief"
	"github.com/edwardmontoya/circle/internal/contract"
	"github.com/edwardmontoya/circle/internal/domain"
	"github.com/edwardmontoya/circle/internal/events"
	"github.com/edwardmontoya/circle/internal/timeline"
)

func init() {
	register(Command{"brief generate", "Render the comprehension gate from .circle/ state", runBriefGenerate})
	register(Command{"brief show", "Print the brief", runBriefShow})
	register(Command{"brief status", "Which items are waiting on a human", runBriefStatus})
	register(Command{"brief approve", "Record the gate event that unblocks writes", runBriefApprove})
	register(Command{"brief reject", "Refuse the plan, with a reason", runBriefReject})
	register(Command{"brief verify", "Declared radius vs. what git says was touched", runBriefVerify})
}

func briefPath(r *contract.Repo, item string) string {
	return r.StateDir("items", item, "brief.md")
}

func runBriefGenerate(e Env, args []string) int {
	f := fs("brief generate", e)
	item := f.String("item", "default", "work item id")
	if err := parse(f, args); err != nil {
		return ExitError
	}
	if f.NArg() > 0 {
		*item = f.Arg(0)
	}
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}

	b, err := brief.Build(repo, *item)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	if len(b.Tasks) == 0 {
		fmt.Fprintf(e.Stderr, "circle: no tasks for %q — run `circle task create` first.\n", *item)
		fmt.Fprintln(e.Stderr, "A brief with nothing to approve is a form, not a gate.")
		return ExitError
	}

	// Regenerating after a plan change silently voids any prior approval,
	// because the hash it was bound to no longer matches.
	prior, _ := brief.LoadApproval(repo, *item, b.PlanHash)
	body := brief.RenderMarkdown(b, prior)

	out := briefPath(repo, *item)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}

	ev := domain.NewEvent(domain.EvBriefGenerate)
	ev.Item, ev.Reason = *item, b.PlanHash
	_ = events.Append(repo, ev)

	p := NewPalette(e.Stdout)
	rel, _ := filepath.Rel(repo.Root, out)
	fmt.Fprintf(e.Stdout, "\n%sBRIEF%s  %s  %splan %s%s\n", p.B, p.N, b.Item, p.D, b.PlanHash, p.N)
	fmt.Fprintf(e.Stdout, "  %s  %d task(s) · %d pattern(s) · %d risk(s)\n",
		rel, len(b.Tasks), len(b.Radius), len(b.Risks))

	if prior != nil && !prior.Valid {
		fmt.Fprintf(e.Stdout, "\n  %s⚠ the previous approval is void: %s%s\n", p.Y, prior.Reason, p.N)
	}
	if prior != nil && prior.Valid {
		fmt.Fprintf(e.Stdout, "\n  %s✓ still approved by %s%s\n", p.G, prior.Approver, p.N)
		return ExitOK
	}
	fmt.Fprintf(e.Stdout, "\n  %sWrites are blocked until a human approves this.%s\n", p.D, p.N)
	fmt.Fprintf(e.Stdout, "  %scircle brief approve %s%s\n\n", p.B, b.Item, p.N)
	return ExitOK
}

func runBriefShow(e Env, args []string) int {
	f := fs("brief show", e)
	item := f.String("item", "default", "work item id")
	if err := parse(f, args); err != nil {
		return ExitError
	}
	if f.NArg() > 0 {
		*item = f.Arg(0)
	}
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}
	b, err := os.ReadFile(briefPath(repo, *item))
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: no brief for %q — run `circle brief generate`\n", *item)
		return ExitPrecond
	}
	e.Stdout.Write(b)
	return ExitOK
}

func runBriefStatus(e Env, args []string) int {
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}
	pending, err := brief.Pending(repo)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	p := NewPalette(e.Stdout)
	if len(pending) == 0 {
		fmt.Fprintf(e.Stdout, "%s✓%s nothing waiting on a human\n", p.G, p.N)
		return ExitOK
	}
	fmt.Fprintf(e.Stdout, "\n%s%d brief(s) waiting on a human%s\n\n", p.Y, len(pending), p.N)
	for _, item := range pending {
		b, err := brief.Build(repo, item)
		if err != nil {
			continue
		}
		fmt.Fprintf(e.Stdout, "  %s%-16s%s %s\n", p.B, item, p.N, b.Title)
		fmt.Fprintf(e.Stdout, "    %s%d task(s) · %d pattern(s) · generated by %s%s\n",
			p.D, len(b.Tasks), len(b.Radius), b.Author, p.N)
	}
	fmt.Fprintln(e.Stdout)
	return ExitOK
}

func runBriefApprove(e Env, args []string) int {
	f := fs("brief approve", e)
	item := f.String("item", "default", "work item id")
	approver := f.String("approver", "", "defaults to git config user.email")
	note := f.String("note", "", "recorded with the approval")
	allowSelf := f.Bool("allow-self", false, "approve a plan you wrote yourself")
	if err := parse(f, args); err != nil {
		return ExitError
	}
	if f.NArg() > 0 {
		*item = f.Arg(0)
	}
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}
	b, err := brief.Build(repo, *item)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	if _, err := os.Stat(briefPath(repo, *item)); err != nil {
		fmt.Fprintf(e.Stderr, "circle: no brief for %q — generate it before approving it.\n", *item)
		fmt.Fprintln(e.Stderr, "Approving a plan nobody rendered is exactly the rubber stamp this gate exists to prevent.")
		return ExitPrecond
	}

	who := *approver
	if who == "" {
		who = gitEmail(repo.Root)
	}
	a, err := brief.Approve(repo, b, who, *note, *allowSelf,
		repo.Contract.Gate.RequireSecondApprover)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitGate
	}

	ev := domain.NewEvent(domain.EvBriefApprove)
	ev.Item, ev.Actor, ev.Reason = *item, who, b.PlanHash
	_ = events.Append(repo, ev)

	p := NewPalette(e.Stdout)
	fmt.Fprintf(e.Stdout, "\n%s✓ approved%s %s by %s\n", p.G, p.N, b.Item, a.Approver)
	if a.SelfApproved {
		fmt.Fprintf(e.Stdout, "  %s⚠ self-approved: you wrote this plan. Recorded as such.%s\n", p.Y, p.N)
	}
	fmt.Fprintf(e.Stdout, "  %splan %s · %d pattern(s) now writable%s\n\n", p.D, a.PlanHash, len(a.Radius), p.N)
	return ExitOK
}

func runBriefReject(e Env, args []string) int {
	f := fs("brief reject", e)
	item := f.String("item", "default", "work item id")
	reason := f.String("reason", "", "required")
	if err := parse(f, args); err != nil {
		return ExitError
	}
	if f.NArg() > 0 {
		*item = f.Arg(0)
	}
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}
	b, err := brief.Build(repo, *item)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	if err := brief.Reject(repo, b, gitEmail(repo.Root), *reason); err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	ev := domain.NewEvent(domain.EvBriefReject)
	ev.Item, ev.Reason = *item, *reason
	_ = events.Append(repo, ev)

	p := NewPalette(e.Stdout)
	fmt.Fprintf(e.Stdout, "%s✗ rejected%s %s — writes remain blocked\n", p.R, p.N, b.Item)
	return ExitOK
}

// runBriefVerify is the instrument the diagram-accuracy metric never had: it
// compares the radius a human approved against what git says was actually
// touched.
func runBriefVerify(e Env, args []string) int {
	f := fs("brief verify", e)
	item := f.String("item", "default", "work item id")
	failOn := f.Bool("fail-on-drift", false, "exit 7 when anything drifted")
	if err := parse(f, args); err != nil {
		return ExitError
	}
	if f.NArg() > 0 {
		*item = f.Arg(0)
	}
	repo, code := openRepo(e)
	if repo == nil {
		return code
	}
	b, err := brief.Build(repo, *item)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitError
	}
	tl, err := timeline.Sync(repo, "default", true)
	if err != nil {
		fmt.Fprintf(e.Stderr, "circle: %v\n", err)
		return ExitExternal
	}

	p := NewPalette(e.Stdout)
	var drifted []string
	for _, path := range tl.TouchedFiles() {
		if !domain.InRadius(path, b.Radius) {
			drifted = append(drifted, path)
		}
	}
	touched := len(tl.TouchedFiles())
	fmt.Fprintf(e.Stdout, "\n%sBRIEF VERIFY%s  %s\n", p.B, p.N, b.Item)
	fmt.Fprintf(e.Stdout, "  %d file(s) touched · %d pattern(s) approved\n", touched, len(b.Radius))
	if len(drifted) == 0 {
		fmt.Fprintf(e.Stdout, "\n  %s✓ every touched file is inside the approved radius%s\n\n", p.G, p.N)
		return ExitOK
	}
	fmt.Fprintf(e.Stdout, "\n  %s⚠ %d outside the approved radius%s\n", p.Y, len(drifted), p.N)
	for _, d := range drifted {
		fmt.Fprintf(e.Stdout, "    %s\n", d)
	}
	fmt.Fprintf(e.Stdout, "\n  %sRecord an addendum, or regenerate the brief and re-approve.%s\n\n", p.D, p.N)
	if *failOn {
		return ExitDrift
	}
	return ExitOK
}

func gitEmail(dir string) string {
	cmd := exec.Command("git", "config", "user.email")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
