package brief

import (
	"fmt"
	"sort"
	"strings"

	"github.com/edwardmontoya/circle/internal/domain"
)

// RenderMarkdown emits brief.md.
//
// This is the committed artifact and it doubles as the PR body: GitHub renders
// mermaid in markdown natively, so the summary a human approved is the same one
// reviewers see, at zero extra cost (D-16).
func RenderMarkdown(b domain.Brief, approval *Approval) string {
	var s strings.Builder

	fmt.Fprintf(&s, "# %s\n\n", b.Title)
	if approval != nil && approval.Valid {
		fmt.Fprintf(&s, "> **Approved** by `%s` at %s. Plan unchanged since.\n\n",
			approval.Approver, approval.At.Format("2006-01-02 15:04 MST"))
	} else {
		s.WriteString("> **Pending approval.** Implementation is blocked: no file is written\n")
		s.WriteString("> until this brief is approved.\n>\n")
		fmt.Fprintf(&s, "> ```\n> circle brief approve %s\n> ```\n\n", b.Item)
	}
	fmt.Fprintf(&s, "`%s` · %d task(s) · %d file pattern(s) · plan `%s`\n\n",
		b.Item, len(b.Tasks), len(b.Radius), b.PlanHash)

	// ---- goal -------------------------------------------------------------
	s.WriteString("## Goal · what done means\n\n")
	if len(b.Tasks) == 0 {
		s.WriteString("_No tasks yet. Run `circle task create` before generating a brief._\n\n")
	}
	for _, t := range b.Tasks {
		mark := "**Verified**"
		how := fmt.Sprintf("`%s`", t.Verify.Gate)
		if t.Verify.Kind == domain.VerifyManual {
			mark = "**Human judgement**"
			how = t.Verify.Reviewer
		}
		fmt.Fprintf(&s, "- %s — %s — %s\n", mark, t.Goal.Statement, how)
	}
	auto, total := domain.MachineCheckable(b.Tasks)
	switch {
	case total == 0:
	case auto == total:
		fmt.Fprintf(&s, "\nAll %d proven by a command. None closes on an assertion.\n\n", total)
	default:
		fmt.Fprintf(&s, "\n%d of %d machine-checkable. The other %d are marked, not hidden — "+
			"their closure is a human's judgement.\n\n", auto, total, total-auto)
	}

	// ---- blast radius -----------------------------------------------------
	s.WriteString("## Blast radius · what this touches\n\n")
	if len(b.Radius) == 0 {
		s.WriteString("_No task declares a path. The write-block cannot be scoped, so it will\n")
		s.WriteString("fall back to allowing any path once approved._\n\n")
	} else {
		s.WriteString("```mermaid\n")
		s.WriteString(moduleDiagram(b))
		s.WriteString("```\n\n")
		s.WriteString("| Pattern | Task |\n|---|---|\n")
		for _, p := range b.Radius {
			fmt.Fprintf(&s, "| `%s` | %s |\n", p, strings.Join(tasksFor(b, p), ", "))
		}
		s.WriteString("\n")
	}

	// ---- plan -------------------------------------------------------------
	s.WriteString("## Plan · in readiness order\n\n")
	s.WriteString("| # | Task | Proven by | Blocked on |\n|---|---|---|---|\n")
	for _, t := range ordered(b.Tasks) {
		dep := "—"
		if len(t.DependsOn) > 0 {
			dep = "`" + strings.Join(t.DependsOn, "`, `") + "`"
		}
		fmt.Fprintf(&s, "| `%s` | %s | `%s` (%s) | %s |\n",
			t.ID, t.Title, t.Verify.Gate, t.Verify.Kind, dep)
	}
	s.WriteString("\n")

	// ---- risks ------------------------------------------------------------
	if len(b.Risks) > 0 {
		s.WriteString("## Risks & unknowns\n\n")
		for _, r := range b.Risks {
			fmt.Fprintf(&s, "- **%s** — %s\n", strings.ToUpper(r.Severity), r.Text)
		}
		s.WriteString("\n")
	}

	// ---- traceability -----------------------------------------------------
	s.WriteString("## Definitions consulted\n\n")
	if len(b.Definitions) == 0 {
		s.WriteString("_None registered._ Nothing in this repository states what should be\n")
		s.WriteString("built, so this plan rests on inference rather than on a specification.\n\n")
	} else {
		for _, d := range b.Definitions {
			if claims, bad := b.Contradicted[d]; bad {
				fmt.Fprintf(&s, "- ~~`%s`~~ — **contradicted by the code**: %s\n",
					d, strings.Join(claims, ", "))
				continue
			}
			fmt.Fprintf(&s, "- `%s`\n", d)
		}
		if len(b.Contradicted) > 0 {
			s.WriteString("\nA struck-through document is registered as authoritative and is not. " +
				"Run `circle knowledge verify` for the evidence, then fix it or drop it — " +
				"planning against a stale definition is worse than planning against none.\n")
		}
		s.WriteString("\n")
	}

	fmt.Fprintf(&s, "---\n\n_Generated by circle from `.circle/` state. "+
		"Structure is derived, not written: every section above is a fact the "+
		"repository already knows._\n")
	return s.String()
}

// moduleDiagram assembles the graph from real signals — the compose map and the
// declared paths — and emits mermaid. Nothing here is imagined.
func moduleDiagram(b domain.Brief) string {
	var s strings.Builder
	s.WriteString("flowchart LR\n")

	if len(b.Services) > 0 {
		for _, svc := range b.Services {
			kind := "infrastructure"
			if svc.IsApp {
				kind = "app"
			}
			fmt.Fprintf(&s, "  %s[\"%s<br/><small>%s</small>\"]\n", ident(svc.Name), svc.Name, kind)
		}
	}
	shown := b.Radius
	if len(shown) > 6 {
		shown = shown[:6]
	}
	for i, p := range shown {
		fmt.Fprintf(&s, "  p%d[\"%s\"]\n", i, p)
		if len(b.Services) > 0 {
			fmt.Fprintf(&s, "  %s --> p%d\n", ident(b.Services[0].Name), i)
		}
	}
	if len(b.Radius) > len(shown) {
		fmt.Fprintf(&s, "  more[\"+%d more pattern(s)\"]\n", len(b.Radius)-len(shown))
	}
	for i := range shown {
		fmt.Fprintf(&s, "  style p%d fill:#E4EAF5,stroke:#2B4E8F,stroke-width:2px\n", i)
	}
	return s.String()
}

func ident(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '-' || r == '.' || r == ' ' {
			return '_'
		}
		return r
	}, s)
}

func tasksFor(b domain.Brief, pattern string) []string {
	var out []string
	for _, t := range b.Tasks {
		for _, p := range t.Paths {
			if p == pattern {
				out = append(out, "`"+t.ID+"`")
				break
			}
		}
	}
	return out
}

// ordered sorts by dependency depth, so the table reads in the order the work
// can actually happen.
func ordered(tasks []domain.Task) []domain.Task {
	idx := map[string]domain.Task{}
	for _, t := range tasks {
		idx[t.ID] = t
	}
	depth := map[string]int{}
	var d func(string, int) int
	d = func(id string, guard int) int {
		if guard > 32 {
			return guard // cyclic; stop rather than recurse forever
		}
		if v, ok := depth[id]; ok {
			return v
		}
		t, ok := idx[id]
		if !ok {
			return 0
		}
		best := 0
		for _, dep := range t.DependsOn {
			if v := d(dep, guard+1) + 1; v > best {
				best = v
			}
		}
		depth[id] = best
		return best
	}
	out := append([]domain.Task(nil), tasks...)
	sort.SliceStable(out, func(i, j int) bool {
		di, dj := d(out[i].ID, 0), d(out[j].ID, 0)
		if di != dj {
			return di < dj
		}
		return out[i].ID < out[j].ID
	})
	return out
}
